project:
  type: website
  output-dir: docs

website:
  title: "Mo-cap on a budget!"
  navbar:
    left:
      - text: "Blog"
        href: /
      - text: "Artefact Design"
        href: artefact_design.qmd
      - outline.qmd
      - progress_report.qmd
    right:
      - icon: github
        href: https://github.com/DanielsHappyWorks/WalkInThePark
      - icon: youtube
        href: https://www.youtube.com/watch?v=dnXfzCFACHY
      - icon: controller
        href: https://boopdood.itch.io/a-walk-in-the-park
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

