project:
  type: website
  output-dir: docs

website:
  title: "mocap-with-kinect"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DanielsHappyWorks/mocap-with-kinect
      - icon: youtube
        href: https://www.youtube.com/channel/UCh4BLIfjlJCQ5Lks4nvvwwA
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

