project:
  type: website
  output-dir: docs

website:
  title: "Mo-cap on a budget!"
  navbar:
    left:
      - text: "Blog"
        href: /
      - about.qmd
    right:
      - icon: github
        href: https://github.com/DanielsHappyWorks/mocap-with-kinect
      - icon: youtube
        href: https://www.youtube.com/channel/UCh4BLIfjlJCQ5Lks4nvvwwA
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

